python_sources()

pex_binary(
    name="send-sms",
    entry_point="send_text.py",
    output_path="send-sms.pex",
)

pex_binary(
    name="font-check",
    entry_point="fontcheck.py",
    output_path="font-check.pex",
)
