#!/usr/bin/env python

import os,re
output = os.popen("nmcli -t --fields name c show --active")
aps = output.read().replace("\n", " ")
# get rid of docker interfaces
aps = re.sub("docker\S*", "", aps).strip()
if aps != "":
    color = "#00FF00"
else:
    aps = "Not Associated"
    color = "#FF0000"
print aps
print aps
print color

