#!/usr/bin/env python

import sys
from bs4 import BeautifulSoup

if len(sys.argv) == 1:
    print("filepath required", file=sys.stderr)
    sys.exit(1)

if sys.argv[1] == "-":
    doc = sys.stdin.read()
else:
    with open(sys.argv[1]) as f:
        doc = f.read()

html = BeautifulSoup(doc, features="html5lib")

for script in html(["script", "style"]):
    script.extract()

text = html.get_text()
lines = [line.strip() for line in text.splitlines()]
chunks = [phrase.strip() for line in lines for phrase in line.split("  ")]
#contents = "\n".join(line for line in lines if line)
contents = "\n".join(chunk for chunk in chunks if chunk)

print(contents)
