#!/usr/bin/env bash

prefix="$HOME/tmpdir"
fname="$prefix-$(openssl rand -hex 5)"
mkdir $fname

for file in "$@"; do
  if [[ -f $file ]]; then
    cp "$file" $fname
  else
    echo "$file" is not a file
  fi
done

echo $fname
