[package]
name = "pserve"
version = "0.1.0"
authors = ["Santiago Verdu <santiago@cl.ly>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
